---
title: "LA River"
author: ""
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggthemes)
library(glue)
library(ggfittext)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE,comment = NA,message = FALSE)


synthesis_curves_dat <- read_csv("raw/SynthesisCurves_SpeciesProb.csv") %>% 
  filter(species.lifestage.hyd %in% c("Typha Adult Depth","Typha Adult Velocity",
                                      "Cladophora Adult Depth","Cladophora Adult Velocity",
                                      "Sas Adult Velocity","Sas Adult Depth",
                                      "Steelhead Prolonged Depth","Sas Juvenile Depth",
                                      "Steelhead Burst Depth","Steelhead Smolts Depth",
                                      "Steelhead Burst Velocity","Typha Seedling Depth"))



dat <- read.csv("raw/FlowRanges_Species_RecUses_Allnodes_04132021.csv",
                encoding = "UTF-8",stringsAsFactors = FALSE) %>% 
  mutate(Species = factor(Species),
         Lower_Limit = as.double(Lower_Limit),
         Upper_Limit = as.double(Upper_Limit),
         Designation_Category = fct_recode(Designation_Category,"Existing"="E",
                                           "Potential"="P",
                                           "Intermittent"="I"),
         Species_Label = fct_recode(Species_Label,
                                    "Current\nFlow"= "Current Flow",
                                    "Willow\nGrowth" = "Willow Growth",
                                    "Willow\nAdult" = "Willow Adult",
                                    "Steelhead\nMigration\n(Prolonged)" = "Steelhead Migration (Prolonged)",
                                    "Typha\nGrowth"= "Typha Growth",
                                    "Typha\nAdult" = "Typha Adult",
                                    "Cladophora\nAdult"= "Cladophora Adult",
                                    "SAS\nGrowth" = "SAS Growth",
                                    "Steelhead\nMigration\n(Smolts)" = "Steelhead Migration (Smolts)",
                                    "Steelhead\nMigration\n(Burst)" = "Steelhead Migration (Burst)",
                                    "Rec.\nUse\nKayak" = "Rec. Use Kayak",
                                    "Rec.\nUse\nFishing" = "Rec. Use Fishing")) %>%
  rename(Seasonal_Component= Seasonal.Component)


dat$Species_Label = fct_relevel(dat$Species_Label,rev)



seasons = dat %>% select(Seasonal_Component) %>% unlist() %>% unique()
names(seasons)=NULL



dat_designated <- dat %>% filter(Designation_BU == "Designated")
dat_not_designated <- dat %>% filter(Designation_BU == "Not Designated")





hex <- tableau_color_pal("Tableau 20")(13)
hex[c(6, 13)] <- c("#999999", "#B07AA1")
species_colors <- setNames(hex, levels(dat$Species_Label))

```

#  {.tabset}

## Optimal Flow Range {.tabset}

```{r}
fluidPage(tags$h3("Location and Season"),
          fluidRow(column(4,
                          radioButtons("location", label = "Select Location:",
                                       choices = c("Node","Reporting Reach",
                                                   "LA River Reach-Master Plan"),
                                       selected="Node")),
                   renderUI({column(4,
                                    if(input$location == "Reporting Reach"){
                                      selectInput("Reach",label = "Specific Location:",
                                                  choices = location_choice() %>%
                                                    unique() %>% sort)
                                    }
                                    else if (input$location == "Node"){
                                      selectInput("Node",label = "Specific Location:",
                                                  choices = location_choice() %>%
                                                    unique)
                                    }
                                    else{
                                      selectInput("MasterLA",label = "Specific Location:",
                                                  choices = location_choice() %>% unique
                                                  %>% sort)
                                    }) }), 
                   column(4,
                          selectInput("season", label = "Select Season:",
                                      choices = c("All",seasons),
                                      selected= c("All",seasons) %>%  .[1]))
          ))

location_choice <- reactive({
  switch(input$location,
         "Reporting Reach" = dat$Reach,
         "Node"= dat$Node,
         "LA River Reach-Master Plan" = dat$waterbody)
})

```

------------------------------------------------------------------------

```{r,eval=FALSE}
# This is the old layout- works but doesnt account for designated/not designated
fluidPage(tags$h3("Beneficial Use Designation"),
          fluidRow(
            column(4,
                   radioButtons("designateBU", label = " Current Designation:",
                                choices = c("Designated","Not Designated"),
                                selected= "Designated")),
            renderUI({
              column(4,
                     selectInput("BU_names", label = "Beneficial Use Name(s):",
                                 choices = BUnames(),
                                 selected = "All")) }),
            renderUI({
              column(4,
                     if(input$designateBU == "Designated"){
                       selectInput("designations", label = "Designation Type:",
                                   choices = c("All","Existing",
                                               "Potential","Intermittent"),
                                   selected= "All")                      
                     }
              )
            }) ))
```



```{r, Beneficial Use Designation}
fluidPage(tags$h3("Beneficial Use Designation"),
                          radioButtons("designateBU", label = " Current Designation:",
                                       choices = c("Designated","Not Designated"),
                                       selected= "Designated"))
          


BUnames <- reactive({
  
  if(input$designateBU == "Designated"){
    
    if(input$location=="Node"){
      validate(need(input$Node != ""," "))
      out <- c("All", dat_designated %>% filter(Node == input$Node) %>% pull(BU_names) %>%
                 str_extract_all('[A-Z]+') %>% unlist() %>% unique() %>% na.omit)
      return(out)    
    }
    else if(input$location == "Reporting Reach"){
      validate(need(input$Reach != ""," "))
      out <- c("All", dat_designated %>% filter(Reach == input$Reach) %>% pull(BU_names) %>%
                 str_extract_all('[A-Z]+') %>% unlist() %>% unique() %>% na.omit)
      return(out)      
    }
    else{
      validate(need(input$MasterLA != ""," "))
      out <- c("All", dat_designated %>% filter(waterbody == input$MasterLA) 
               %>% pull(BU_names) %>% str_extract_all('[A-Z]+') %>% unlist() 
               %>% unique() %>% na.omit)
      return(out)       
    }
  }
  else{
    if(input$location=="Node"){
      validate(need(input$Node != ""," "))
      out <- c("All", dat_not_designated %>% filter(Node == input$Node) %>% pull(BU_names) %>%
                 str_extract_all('[A-Z]+') %>% unlist() %>% unique() %>% na.omit)
      return(out)    
    }
    else if(input$location == "Reporting Reach"){
      validate(need(input$Reach != ""," "))
      out <- c("All", dat_not_designated %>% filter(Reach == input$Reach) %>% pull(BU_names) %>%
                 str_extract_all('[A-Z]+') %>% unlist() %>% unique() %>% na.omit)
      return(out)      
    }
    else{
      validate(need(input$MasterLA != ""," "))
      out <- c("All", dat_not_designated %>% filter(waterbody == input$MasterLA) 
               %>% pull(BU_names) %>% str_extract_all('[A-Z]+') %>% unlist() 
               %>% unique() %>% na.omit)
      return(out)       
    }  
  }
  
})


fluidPage(
  fluidRow(column(4, 
                  renderUI({
                    selectInput("BU_names", label = "Beneficial Use Name(s):",
                                choices = BUnames(),
                                selected = "All") })),
           renderUI({
             column(4,
                    if(input$designateBU == "Designated"){
                      selectInput("designations", label = "Designation Type:",
                                  choices = c("All","Existing",
                                              "Potential","Intermittent"),
                                  selected= "All")                      
                    })
           })
  ))
```









------------------------------------------------------------------------

```{r}
fluidPage(tags$h3("Species"),
          fluidRow(
            column(4,
                   selectInput("probthresh", label = "Probability of Occurrence:",
                               choices = c("Medium","High"),
                               selected= "Medium")),
            column(4,
                   radioButtons("synthesis",label="Species Synthesis:",
                                choices=c("Yes","No"),
                                selected="No")),
            renderUI({
              column(4,
                     if(input$synthesis == "Yes"){
                       radioButtons("synthesis_type",label="Type of Species Synthesis:",
                                    choices=c("Single","Multiple"),
                                    selected="Single")
                     }
              )
            })
          ))
```


If Species Synthesis is Yes - synthesis ruleset applied to get overall flow recommendations

Otherwise, flow recommendations by individual life stages


------------------------------------------------------------------------

```{r}
boxplot_dat <- reactive({
  validate(need(input$designations != ""," "))
  
  if(input$season != "All"){
    season = input$season
  }
  else{
    season = seasons
  }
  
  if(input$designations == "All"){
    designate_category = c("Existing","Intermittent", "Potential")
  }
  else{
    designate_category = input$designations
  }
  
  if(input$BU_names != "All"){
    beneficial_use_names = dat$BU_names[grep(input$BU_names,dat$BU_names)]
  }
  else{
    beneficial_use_names = unique(dat$BU_names)
  }
  
  if(input$location == "Node"){
    validate(need(input$Node != ""," "))
    out <- dat %>% filter(Node == input$Node,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          BU_names %in% beneficial_use_names|is.na(BU_names),
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                                        "Peak_2 as lower, Peak_10 as upper")|
                            is.na(metric)) %>% 
      mutate(Species_Label = fct_drop(Species_Label))
  }
  else if(input$location == "Reporting Reach"){
    validate(need(input$Reach != ""," "))
    out <- dat %>% filter(Reach == input$Reach,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          BU_names %in% beneficial_use_names|is.na(BU_names),
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                                        "Peak_2 as lower, Peak_10 as upper")| is.na(metric)) 
  }
  else{
    validate(need(input$MasterLA != ""," "))
    out <- dat %>% filter(waterbody == input$MasterLA,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          BU_names %in% beneficial_use_names|is.na(BU_names),
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                                        "Peak_2 as lower, Peak_10 as upper")| is.na(metric))   
  }
  return(out)
})
```

```{r}
box_plot <- reactive({
  
  dat <- boxplot_dat()
  
  if(input$location=="Node"){
    dat <- dat %>% 
      filter(!is.na(Lower_Limit), !is.na(Upper_Limit)) %>% 
      mutate(flow_range = str_c(floor(Lower_Limit), ceiling(Upper_Limit), sep = '-'))
    dat2 <- dat %>% 
      distinct(Seasonal_Component, species, Species_Label, Lower_Limit, Upper_Limit) %>% 
      group_by(Seasonal_Component, species) %>% 
      mutate(count = n()) %>% 
      mutate(Lower_Limit = max(Lower_Limit, na.rm = T), 
             Upper_Limit = min(Upper_Limit, na.rm = T)) %>% 
      mutate(species_type = ifelse(str_detect(Species_Label, 'Growth'), 'Min',
                                   ifelse(str_detect(Species_Label, 'Adult'), 'Max', NA))) %>% 
      ungroup() %>% filter(count > 1, !is.na(species_type))

    ADDBOX <- FALSE
    if(nrow(dat2) > 0) {
      ADDBOX <- TRUE
      dat2 <- dat2 %>% 
        pivot_wider(names_from = species_type, values_from = Species_Label) %>% 
        mutate(label_range = glue::glue("{species}:\n{range} cfs", species = species, range = str_c(Lower_Limit, Upper_Limit, sep = '-')),
               yloc = (Lower_Limit + Upper_Limit)/2,
               xloc = (as.numeric(Min) + as.numeric(Max))/2)
    } 
    
    ggplot() + 
      geom_rect(aes(xmin = as.factor(as.numeric(Species_Label) - 0.4), 
                    xmax = as.factor(as.numeric(Species_Label) + 0.4),
                    ymin = Lower_Limit,
                    ymax = Upper_Limit, fill = Species_Label), color = 'black', data = dat) +
      geom_text(aes(x = as.factor(as.numeric(Species_Label)), y = Upper_Limit, 
                    label = flow_range, vjust = -0.5), data = dat, size = 4) +
      {if(ADDBOX) list(geom_rect(aes(xmin = as.factor(as.numeric(Min) - 0.4), 
                                xmax = as.factor(as.numeric(Max) + 0.4), 
                                ymin = Lower_Limit, ymax = Upper_Limit),
                            data = dat2, fill = 'black', alpha = 0.4, color = 'black', size = 1),
          ggfittext::geom_fit_text(aes(xmin = as.factor(as.numeric(Min) - 0.4),
                                       xmax = as.factor(as.numeric(Max) + 0.4),
                                       ymin = Lower_Limit,
                                       ymax = Upper_Limit, label = label_range, fontface = 'bold'),
                                   data = dat2, contrast = T, reflow = T,
                                   na.rm = T, size = 12))} +
      scale_x_discrete(breaks = 1:nlevels(dat$Species_Label), labels = levels(dat$Species_Label)) +
      facet_wrap(~ Seasonal_Component, scales="free", drop = F) +
      theme(strip.text = element_text(face = "bold", size = 12),
            strip.background = element_rect(fill = "white", 
                                            colour = "black",size = 1)) +
      scale_fill_manual(name = "Species", values = species_colors) +
      theme(legend.position = "bottom",
            panel.grid.minor.y = element_blank()) +
      labs(title="Flow Ranges", x = "", y = "Flow (cfs)") +
      scale_y_log10()
  }
  else{
    ggplot(dat,aes(x=Species_Label, ymin = Lower_Limit,
                   lower = Lower_Limit,middle=(Lower_Limit+Upper_Limit)/2,
                   upper = Upper_Limit, ymax = Upper_Limit,
                   fill= Species_Label)) +
      geom_boxplot(stat = "identity",fatten=NULL) +
      facet_grid(Node~ Seasonal_Component, scales="free") +
      theme(strip.text = element_text(face="bold", size=12),
            strip.background = element_rect(fill="white", 
                                            colour="black",size=1)) +
      # scale_fill_colorblind()+
      scale_fill_manual(values = species_colors) +
      theme(legend.position="bottom",
            panel.grid.minor.y = element_blank(),
      ) +
      labs(title="Flow Ranges",x ="", y = "Flow (cfs)",
           fill="Species - Lifestage")+
      scale_y_log10()   
  }
})


```

```{r}
output$boxfig <- downloadHandler(
  filename = function() {
    if(input$location=="Node"){
      paste(input$Node, '.png', sep='') 
    }
    else if(input$location == "Reach"){
      paste(input$Reach, '.png', sep='') 
    }
    else{
      paste(input$MasterLA, '.png', sep='') 
    }},
  content = function(file) {
    ggsave(file, plot = box_plot(), device = "png",
           width = 30, height = 20, units = "cm")
  }
)

output$boxdat <- downloadHandler(
  filename = function() {
    if(input$location=="Node"){
      paste(input$Node, '.csv', sep='') 
    }
    else if (input$location == "Reach"){
      paste(input$Reach, '.csv', sep='') 
    }
    else{
      paste(input$MasterLA, '.csv', sep='')         
    }},
  content = function(file) {
    write.csv(boxplot_dat(), file, quote = T, row.names = F)
  }
)

```


```{r}
fluidPage(
downloadButton('boxdat', 'Download Data'),
downloadButton('boxfig', 'Download Boxplot')
)
renderPlot({box_plot()},height=600,width=1100)
```




```{r}
ranges_print <- function(x)
{
  ranges = round(range(x),2)
  paste(ranges[1],"-",ranges[2])
}


is_integer0 <- function(x)
{
  is.integer(x) && length(x) == 0L
}
```


```{r}
synthesis <- reactive({
  
  filter_check <- boxplot_dat() %>% filter(!Species %in% c("Rec. Use - Kayak",
                                                           "Rec. Use - Fishing",
                                                           "Current Flow"))
  if(input$season != "All"){
    
    if(nrow(filter_check)==0){
      dat <-  boxplot_dat() %>% filter(Species %in% c("Rec. Use - Kayak",
                                                      "Rec. Use - Fishing",
                                                      "Current Flow")) %>%
        group_by(Seasonal_Component,Species) %>%
        select(Species,Lower_Limit,Upper_Limit)  %>%
        summarise(ranges = list(seq(from = Lower_Limit,to = Upper_Limit))) %>% 
        group_split()
    }
    else{
      dat <-  boxplot_dat() %>% filter(!Species %in% c("Rec. Use - Kayak",
                                                       "Rec. Use - Fishing",
                                                       "Current Flow")) %>%
        group_by(Seasonal_Component,Species) %>%
        select(Species,Lower_Limit,Upper_Limit)  %>%
        summarise(ranges = list(seq(from = Lower_Limit,to = Upper_Limit))) %>% 
        group_split()
    }
    season = input$season
    names(dat) = season
    
    seasonal_ranges = list()
    seasonal_species = list()
    
    for(i in 1:length(dat)){
      seasonal_ranges[[i]] = dat %>%
        pluck(i) %>%
        group_by(Species) %>%
        pluck("ranges")
    }
    for(i in 1:length(dat)){
      seasonal_species[[i]] = dat %>%
        pluck(i,"Species")
    }
    
    names(seasonal_ranges) = season
    names(seasonal_species) = NULL
    
    names(seasonal_ranges[[season]]) =unlist(seasonal_species) %>% as.character() 
    ranges = lapply(seasonal_ranges[[season]],ranges_print)
    
    out <- tibble("Season" = season,
                  "Species" = unlist(seasonal_species) %>% as.character(),
                  "Ranges (cfs)" = unlist(ranges))
    return(list("Table"=out,seasonal_ranges))
  }
  else{
    out <- boxplot_dat() %>% select(Seasonal_Component,Species,
                                    Lower_Limit,Upper_Limit) %>%
      rename(Season = Seasonal_Component) %>%
      group_by(Season,Species) %>%
      summarise(Ranges = list(seq(from = Lower_Limit,to = Upper_Limit) %>%
                                ranges_print))
    return(out)
  }
})


synthesis_current_flows <- reactive({
  
  flows <- boxplot_dat() %>% filter(Species=="Current Flow") %>%
    group_by(Seasonal_Component) %>%
    select(Species,Lower_Limit,Upper_Limit) %>%
    summarise(ranges = list(seq(from = Lower_Limit,to = Upper_Limit))) %>%
    pull(ranges)  
  
  if(input$season != "All"){
    
    season = input$season
    names(flows) = season
    
    out <- flows %>% pluck(season) %>% ranges_print
    
    return(out)
  }
  else{
    return(NULL)
  }
})


```



```{r}
DT::renderDataTable({
  if(input$synthesis == "Yes" & input$location == "Node"){
    if(input$synthesis_type == "Single"){
      if(input$season != "All"){
        
        choices <- synthesis()[["Table"]] %>% pull(Species) %>%
          strsplit(" - ") %>%
          unlist() %>%
          unique() %>%
          str_trim() %>% .[.!="Adult"] %>%  .[.!="Growth"]
        
        choices_ranges = c()
        
        for(i in 1:length(choices)){
          choices_ranges[i] = Reduce(intersect,
                                     synthesis()[[2]][[input$season]][grep(choices[i],
                                                                           synthesis()[[1]] %>%
                                                                             pull(Species))]) %>%
            ranges_print()
        }
        out <- tibble(Season = input$season,
                      Species = choices,
                      Ranges = choices_ranges ,
                      "Current Flow (cfs)" = synthesis_current_flows())
        return(out)
      }
      else{
        synthesis()
      }}
    else{
      if(input$season != "All"){
        species_season <- synthesis()[["Table"]] %>% pull(Species) %>%
          unlist() %>%
          unique()
        
        species_list = list()
        for(i in 1:length(species_season)){
          
          species_list[[i]] = suppressWarnings(
            as_tibble(species_season %>% combn(i) %>% t()) %>%
              rowwise() %>%
              mutate(Ranges = Reduce(intersect,
                                     synthesis()[[2]][[input$season]][
                                       grep(str_c(c_across(),collapse = "|"),
                                            species_season)]) %>% 
                       range() %>% ranges_print()) %>% 
              mutate(Range_Diff = Reduce(intersect,
                                         synthesis()[[2]][[input$season]][
                                           grep(str_c(c_across(),
                                                      collapse = "|"),
                                                species_season)])
                     %>% range() %>% diff()) %>%
              filter(Range_Diff != "-Inf") %>%
              ungroup() %>%
              top_n(Range_Diff,n=1))
        }
        
        
        multiple_synthesis <- discard(species_list, function(x) nrow(x) == 0) %>%
          last() %>% select(-c("Range_Diff"))
        
        names(multiple_synthesis)[-length(multiple_synthesis)] <- paste0("Species ",
                                                                         seq_along(multiple_synthesis[-length(multiple_synthesis)]))
        return(multiple_synthesis)
      }
      else{
        synthesis()
      }
    }}
},options = list(dom = 't'))
```



```{r, eval=FALSE}
renderDataTable({ 
  species_season <- synthesis()[["Table"]] %>% pull(Species) %>%
    unlist() %>%
    unique()
  
  species_list = list()
  for(i in 1:length(species_season)){
    
    species_list[[i]] = suppressWarnings(
      as_tibble(species_season %>% combn(i) %>% t()) %>%
        rowwise() %>%
        mutate(Ranges = Reduce(intersect,
                               synthesis()[[2]][[input$season]][
                                 grep(str_c(c_across(),collapse = "|"),
                                      species_season)]) %>% 
                 range() %>% ranges_print()) %>% 
        mutate(Range_Diff = Reduce(intersect,
                                   synthesis()[[2]][[input$season]][
                                     grep(str_c(c_across(),
                                                collapse = "|"),
                                          species_season)])
               %>% range() %>% diff()) %>%
        filter(Range_Diff != "-Inf") %>%
        ungroup() %>%
        top_n(Range_Diff,n=1))
  }
  
  
  multiple_synthesis <- discard(species_list, function(x) nrow(x) == 0) %>%
    last()
  
  multiple_synthesis %>% select(-c("Range_Diff")) %>%
    unlist(use.names = FALSE)
})
```





## Sensitivity Curves
