---
title: "LA River"
author: ""
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(forcats)
library(ggthemes)

knitr::opts_chunk$set(echo = FALSE,warning = FALSE,comment = NA,message = FALSE)

dat <- read.csv("raw/FlowRanges_Species_RecUses_Allnodes_BU_03172021.csv",
                encoding = "UTF-8",stringsAsFactors = FALSE) %>% 
  mutate(Species = factor(Species),
         Species_Label = gsub(" ", "\n",Species_Label),
         Species_Label = factor(Species_Label,
                                levels = c("Willow\nGrowth", "Willow\nAdult",
                                           "Typha\nGrowth","Typha\nAdult",
                                           "Cladophora\nAdult", "Current\nFlow",
                                           "SAS\nGrowth","SAS\nAdult",
                                           "Steelhead\nMigration\n(Prolonged)",
                                           "Steelhead\nMigration\n(Burst)",
                                           "Steelhead\nMigration\n(Smolts)",
                                           "Rec.\nUse\nKayak",
                                           "Rec.\nUse\nFishing")),
         Lower_Limit = as.double(Lower_Limit),
         Upper_Limit = as.double(Upper_Limit),
         Designation_Category = fct_recode(Designation_Category,"Existing"="E",
                                           "Potential"="P",
                                           "Intermittent"="I")) %>%
  rename(Seasonal_Component= Seasonal.Component)
         
         
seasons = dat %>% select(Seasonal_Component) %>% unlist() %>% unique()
names(seasons)=NULL

```

#  {.tabset}

## Optimal Flow Range {.tabset}

```{r}
fluidPage(tags$h3("Location and Season"),
          fluidRow(column(4,
radioButtons("location", label = "Select Location:",
             choices = c("Node","Reporting Reach",
                         "LA River Reach-Master Plan"),
             selected="Node")),
renderUI({column(4,
                 if(input$location == "Reporting Reach"){
                   selectInput("Reach",label = "Specific Location:",
                               choices = location_choice() %>%
                                 unique() %>% sort)
                   }
                 else if (input$location == "Node"){
                   selectInput("Node",label = "Specific Location:",
                               choices = location_choice() %>%
                                 unique)
                   }
                 else{
                 selectInput("MasterLA",label = "Specific Location:",
                             choices = location_choice() %>% unique
                             %>% sort)
                   }) }), 
column(4,
       selectInput("season", label = "Select Season:",
                   choices = c("All",seasons),
                   selected= c("All",seasons) %>%  .[1]))
                 ))

location_choice <- reactive({
  switch(input$location,
         "Reporting Reach" = dat$Reach,
         "Node"= dat$Node,
         "LA River Reach-Master Plan" = dat$waterbody)
  })
```

------------------------------------------------------------------------

```{r}
fluidPage(tags$h3("Beneficial Use Designation"),
          fluidRow(
            column(4,
                   radioButtons("designateBU", label = " Current Designation:",
                                choices = dat$Designation_BU %>% 
                                  unique() %>% .[-1],
                                selected= dat$Designation_BU %>% 
                                  unique() %>% .[2])),
            column(4,
                   selectInput("BU_names", label = "Beneficial Use Name(s):",
                               choices = c("All","WILD","RARE",
                                           "EST","MIGR","COLD","SPWN"),
                               selected = "ALL")),
            column(4,
                   selectInput("designations", label = "Designation Type:",
                               choices = c("All","Existing",
                                           "Potential","Intermittent"),
                               selected= "All"))))
```

------------------------------------------------------------------------

```{r}
fluidPage(tags$h3("Species"),
          fluidRow(
          column(4,
          selectInput("probthresh", label = "Probability of Occurrence:",
                      choices = dat$Probability_Threshold %>% unique() %>% .[-1],
                      selected= dat$Probability_Threshold %>% unique()
                      %>% .[2])),
          column(4,
                 radioButtons("synthesis",label="Species Synthesis:",
                              choices=c("Yes","No"),
                              selected="No"))
          ))
```


If Species Synthesis is Yes - synthesis ruleset applied to get overall flow recommendations

Otherwise, flow recommendations by individual life stages


------------------------------------------------------------------------

```{r}
boxplot_dat <- reactive({
  if(input$season != "All"){
    season = input$season
  }
  else{
    season = seasons
  }
  
  if(input$designations != "All"){
    designate_category = input$designations
  }
  else{
    designate_category = dat$Designation_Category %>% unique %>% .[-1]
  }
  
  if(input$BU_names != "All"){
    beneficial_use_names = dat$BU_names[grep(input$BU_names,dat$BU_names)]
  }
  else{
    beneficial_use_names = dat$BU_names  %>% strsplit(",") %>%
      unlist() %>% unique() %>% str_trim()
  }
  
  if(input$location == "Node"){
    out <- dat %>% filter(Node == input$Node,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          BU_names %in% beneficial_use_names,
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                          "Peak_2 as lower,Peak_10 as upper")| is.na(metric))
  }
  else if(input$location == "Reporting Reach"){
    out <- dat %>% filter(Reach == input$Reach,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                          "Peak_2 as lower,Peak_10 as upper")| is.na(metric)) 
  }
  else{
    out <- dat %>% filter(waterbody == input$MasterLA,
                          Designation_BU == input$designateBU |is.na(Designation_BU),
                          Seasonal_Component %in% season,
                          Designation_Category %in% designate_category |
                            is.na(Designation_Category),
                          Probability_Threshold == input$probthresh|
                            is.na(Probability_Threshold),
                          metric %in% c("DS_Mag_50","Wet_BFL_Mag_10",
                          "Peak_2 as lower,Peak_10 as upper")| is.na(metric))   
  }
  return(out)
})
```

```{r}
box_plot <- reactive({
  
  dat <- boxplot_dat()
  
  if(input$location=="Node"){  
    ggplot(dat,aes(x=Species_Label, ymin = Lower_Limit,
                   lower = Lower_Limit,middle=(Lower_Limit+Upper_Limit)/2,
                   upper = Upper_Limit, ymax = Upper_Limit,
                   fill= Species_Label)) +
      geom_boxplot(stat = "identity",fatten=NULL) +
      facet_wrap(~ Seasonal_Component, scales="free") +
      theme(strip.text = element_text(face="bold", size=12),
            strip.background = element_rect(fill="white", colour="black",size=1)) +
      scale_fill_colorblind()+
      theme(legend.position="bottom",
            panel.grid.minor.y = element_blank()) +
      labs(title="Flow Ranges",x ="", y = "Flow (cfs)",
           fill= "Species - Lifestage")+
  scale_y_log10()
    }
  else{
    ggplot(dat,aes(x=Species_Label, ymin = Lower_Limit,
                   lower = Lower_Limit,middle=(Lower_Limit+Upper_Limit)/2,
                   upper = Upper_Limit, ymax = Upper_Limit,
                   fill= Species_Label)) +
      geom_boxplot(stat = "identity",fatten=NULL) +
      facet_grid(Node~ Seasonal_Component, scales="free") +
      theme(strip.text = element_text(face="bold", size=12),
            strip.background = element_rect(fill="white", colour="black",size=1)) +
      scale_fill_colorblind()+
      theme(legend.position="bottom",
            panel.grid.minor.y = element_blank(),
            ) +
      labs(title="Flow Ranges",x ="", y = "Flow (cfs)",fill="Species - Lifestage")+
  scale_y_log10()   
  }
  })


```

```{r}
renderPlot({box_plot()},height=600,width=1100)

output$boxfig <- downloadHandler(
    filename = function() {
      if(input$location=="Node"){
        paste(input$Node, '.png', sep='') 
      }
      else if(input$location == "Reach"){
        paste(input$Reach, '.png', sep='') 
      }
      else{
        paste(input$MasterLA, '.png', sep='') 
      }},
    content = function(file) {
        ggsave(file, plot = box_plot(), device = "png",
               width = 30, height = 20, units = "cm")
    }
)

output$boxdat <- downloadHandler(
    filename = function() {
      if(input$location=="Node"){
        paste(input$Node, '.csv', sep='') 
      }
      else if (input$location == "Reach"){
        paste(input$Reach, '.csv', sep='') 
      }
      else{
        paste(input$MasterLA, '.csv', sep='')         
      }},
    content = function(file) {
      write.csv(boxplot_dat(), file, quote = T, row.names = F)
    }
)

```


```{r}
fluidPage(
downloadButton('boxdat', 'Download Data'),
downloadButton('boxfig', 'Download Boxplot')
)
```




## Sensitivity Curves
